apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sveltekit-app
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
    - host: yourapp.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sveltekit-app
                port:
                  number: 80
