apiVersion: v1
kind: Service
metadata:
  name: sveltekit-app
  labels:
    app: sveltekit-app
spec:
  selector:
    app: sveltekit-app
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP
